template-file-path: networking/vpc.yaml
parameters:
  PublicSubnet2CIDR: 10.0.2.0/24
  VpcCIDR: 10.0.0.0/16
  DBSubnet1CIDR: 10.0.5.0/24
  EnvironmentName: dev
  AppSubnet2CIDR: 10.0.4.0/24
  DBSubnet2CIDR: 10.0.6.0/24
  AppSubnet1CIDR: 10.0.3.0/24
  PublicSubnet1CIDR: 10.0.1.0/24
tags: {}
