AWSTemplateFormatVersion: '2010-09-09'
Description: Create a basic VPC only

Parameters:
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MySimpleVPC

Outputs:
  VpcId:
    Description: ID of the created VPC
    Value: !Ref MyVPC
